### ISSUE TITLE
Gráficos fuera de lugar

### ISSUE THREAD

**Issue by maikol-solis** [CisarUli/Bitacoras-Grupo-6-CA-0204-II-2024-#2]
Hola @phL-0x y @CisarUli 

¿Cuál es el motivo de agregar estos gráficos? 

https://github.com/CisarUli/Bitacoras-Grupo-6-CA-0204-II-2024-/commit/9f504212b9f9f5ed23c3a9793f4c1cdca735a0b7

https://github.com/CisarUli/Bitacoras-Grupo-6-CA-0204-II-2024-/commit/2edfcbde2e701cc607c93952e502f37ef5da03fc

https://github.com/CisarUli/Bitacoras-Grupo-6-CA-0204-II-2024-/commit/dcec9ad1a62a6ff02cb702e6c752ce35f883efdd

No tienen relación con su trabajo ya que estos son del repositorio de ejemplo que le envié hace algunas semanas. 

Saludos.

**Comment by maikol-solis** [comment]
Buenos días. 

Veo que eliminaron los gráficos, pero cuidado ya que commit no está en formato convencional. b391377cf6e1cb9c808ae5a79e91e2130139fa15

Saludos.

**Comment by ghost** [comment]
Buenos días profesor @maikol-solis ,

Entendido, estoy de acuerdo. Los eliminé, y pronto el commit estará corregido. 

Saludos,

Pablo Chaves.

**Comment by ghost** [comment]
Buenas tardes profesor @maikol-solis ,

El commit ya está reescrito. 

Atentamente,

Pablo Chaves.
