### ISSUE TITLE
¿Cuál es el sentido de esta parte? 

### ISSUE THREAD

**Issue by maikol-solis** [CisarUli/Bitacoras-Grupo-6-CA-0204-II-2024-#3]
¿Para qué complicarse la vida con un modelo de series de tiempo si el objetivo del proyecto es solamente hacer un análisis descriptivo? 

Si hacen esto, deben hacer todas las pruebas de hipótesis correspondientes para verificar que su modelo tenga sentido, si no simplemente estaría mal calibrado. 

https://github.com/CisarUli/Bitacoras-Grupo-6-CA-0204-II-2024-/blob/693bafa77cf57d7d0b6a367ce780ed3b86ec9fdb/bitacora-3.qmd#L673-L707

**Comment by CisarUli** [comment]
Buenas noches profe .

Gracias por la observación, fue una confusión respecto a lo que se solicitaba en el proyecto, procederé a eliminar la parte del modelo ARIMA para solo tener el análisis descriptivo solicitado.

**Comment by maikol-solis** [comment]
Con gusto. Saludos.
